export enum Messages {
  health = 'Im still alive ᕕ(ಠ‿ಠ)ᕗ',
  createdSuccess = 'Created successful',
  createdError = 'An error occurred during creation',
  creationBegin = 'Creations Begin',
  creationEnding = 'Creation Ending',
  updatedSuccess = 'Updated successful',
  updatedError = 'An error occurred during the update',
  updateBegin = 'Update Begin',
  UpdateEnding = 'Update ending',
  findSuccess = 'Search results were found for:',
  findNotFound = 'No search results found for:',
  queryBegin = 'Querying Begin',
  queryEnding = 'Querying Ending',
  filtersNotResult = 'No records found for selected filters',
}
